### ISSUE TITLE
Mechanical Engineering is the ONLY Engineering

### ISSUE THREAD

**Issue by ghost** [bigrando420/thomas#10]
This post is in response to the stupid & disrespectful claims made against engineering, when you mentioned the word "Engineered" in one of your videos (I RELEASED MY FIRST VIDEO GAME). You know nothing about engineering, and you have no capacity to talk about the subject. Engineering is a serious subject, and has nothing to do with an easy job like software devs/scriptkiddies hiding behind keyboards and writing code. 
Please stop acting like a wannabe. There is no such thing as "software" "engineering". That is the most pathetic claim ever. Quit being disrespectful to Engineering. You know nothing about what Engineering entails. Engineering means designing, building and producing real mechanical systems, like turbojets and vehicular engines. It has nothing to do with sitting behind a keyboard and writing code or making games. Software & game dev is easy and for kids. And it has absolutely nothing to do with a serious and real subject like Engineering (Mechanical Engineering is the ONLY Engineering). Software devs are ultra clowns and wannabes, who know nothing about engineering. They're just scummy liars who act like tryhards when they talk about a great subject like Engineering (Mechanical Engineering is the ONLY Engineering). Ya'll will never even come close to an engineer. So quit making false claims against engineering. And stop being disrespectful to real Engineers (Mechanical Engineering is the ONLY Engineering). 

Mechanical Engineering is the ONLY Engineering. It has always been like that, and will remain like that forever, period. :)
Bye bye.

**Comment by randyprime** [comment]
sounds like you needa go engineer some bitches
