### ISSUE TITLE
No telescope/base source files

### ISSUE THREAD

**Issue by c4llv07e** [bigrando420/thomas#2]
`telescope_light.c` requires `third_party/telescope/base/base_types.c` and `third_party/telescope/base/base_math.c` which are not there, only their headers. Because of this, I can't build it.

Does this have something to do with the telescope's closed source code?

**Comment by bigrando420** [comment]
Yup, closed source. Building from source will be impossible now unless you're on windows and just link to the .dll

My goal here isn't to be building on other platforms however (at the moment). This repo will mainly just be used as a resource for me to link my source code to.

**Comment by c4llv07e** [comment]
Ok, thank you for answer.
