### ISSUE TITLE
Use CMake instead of Visual Studio project files

### ISSUE THREAD

**Issue by TheKnarf** [bigrando420/thomas#3]
Using CMake will allow people who use other code editors (like VSCode, Vim, Sublime Text, CLion) to build the project without being dependent on Visual Studio. CMake also works with Visual Studio, so this will not force you to move away form it, just open up for making it easier to switch and go between code editors.

**Comment by bigrando420** [comment]
It's not dependent on Visual Studio. I use VS to call the `build.bat`, which is a concept that can be applied to all editors, ones that don't even support CMake. The only thing it's dependent on is MSVC.
