### ISSUE TITLE
Union and Struct initialization 

### ISSUE THREAD

**Issue by wutzig** [bigrando420/thomas#4]
On Visual Studio 2022 with the current build config I get compiler errors C2440  'initializing': cannot convert from 'initializer list' to 'Vec2' in numerous places. Changing all Vec2 and Vec4 initialization to curly brackets `Vec2 vec { 16, 0 };` according to [cppreference](https://en.cppreference.com/w/c/language/struct_initialization) seems to fix this.
Really cool project, by the way :-)

**Comment by randyprime** [comment]
Just converted project back to C, this should be fixed now.
