### ISSUE TITLE
How to use? 

### ISSUE THREAD

**Issue by jacksonhead** [bigrando420/thomas#5]
![image](https://user-images.githubusercontent.com/31589563/198864011-f32e8915-0918-4e06-adf1-5413aa4ca60f.png)

**Comment by randyprime** [comment]
My current project is basically one big example. I'll probably have a more definitive boiler-plate example a couple projects down the line, but no promises. Like I said in the readme, tear out what you need for your own projects. This isn't meant to be cloned and used.
